services:
  speechfire:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WHISPER_MODEL=${WHISPER_MODEL:-base}
    ports:
      - "${SERVER_HOST:-127.0.0.1}:${SERVER_PORT:-5000}:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DOCKER_ENV=1
      - SERVER_HOST=${SERVER_HOST:-0.0.0.0}
      - SERVER_PORT=5000
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - speechfire-network

networks:
  speechfire-network:
    driver: bridge